name: Run tests
on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run my tests
              uses: sudo-bot/action-shunit2@latest
              with:
                  cli: "./tests/test-set-licensetype.sh"
